version: '2.1'
services:
  client:
    build: ./client
    ports:
      - '80:80'
    volumes:
      - ${PWD}/client/dist:/usr/share/nginx/html

  app:
    build: ./app
    command: 'yarn run dev'
    expose:
      - '3000'
      - '61614'
    ports:
      - '3000:3000'
      - '61614:61614'
    environment:
      PORT: 3000
      BROKER_HOST: broker
      BROKER_PORT: 61613
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      CHUNK_SIZE: 1048576 # 1MB
      UPLOADS_PATH: /workspace/uploads
      QUEUE_NAME: /queue/upload
    volumes:
      - ${PWD}/app:/workspace
      - ${PWD}/tmp:/workspace/uploads
      - /workspace/node_modules

  rabbitmq:
    build: ./rabbitmq
    expose:
      - '5672'  # amqp
      - '61613' # stomp
    ports:
      - '15672:15672' # management console

  mongo:
    image: mongo:3.4
    ports:
      - '27017'

  redis:
    image: redis:alpine
    ports:
      - '6379'

  worker:
    build: ./worker
    command: 'yarn run dev'
    expose:
        - '3001'
    environment:
      PORT: 3001
      BROKER_HOST: broker
      BROKER_PORT: 61613
      QUEUE_NAME: /queue/upload
      TOPIC_RESOURCE: /topic/chunk
    volumes:
      - ${PWD}/worker:/workspace
      - ${PWD}/tmp:/tmp/uploads
      - /workspace/node_modules
