version: '2'
services:
  express:
    build: .
    expose:
      - '3000'
      - '61614'
    ports:
      - '3000:3000'
      - '61614:61614'
    command: 'npm run dev'
    volumes:
      - ${PWD}:/workspace